{% set name = "verde" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 274d52f459e5e6f696bacab49b4630692825151c1b8a7be672bd89a95b48d0c2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - numpy >=1.19
    - scipy >=1.5
    - pandas >=1.1
    - xarray >=0.16
    - scikit-learn >=0.24
    - pooch >=1.2
    - dask >=2021.05.0

test:
  requires:
    - pytest
    - pyproj
  imports:
    - verde
  commands:
    - pytest --pyargs verde.tests.test_minimal

about:
  home: http://github.com/fatiando/verde
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Processing and gridding spatial data, machine-learning style
  description: |
    Verde is a Python library for processing spatial data (topography, 
    point clouds, bathymetry, geophysics surveys, etc) and interpolating 
    them on a 2D surface (i.e., gridding) with a hint of machine learning.
    Our core interpolation methods are inspired by machine-learning. As 
    such, Verde implements an interface that is similar to the popular 
    scikit-learn library. We also provide other analysis methods that are 
    often used in combination with gridding, like trend removal, 
    blocked/windowed operations, cross-validation, and more!
  doc_url: https://www.fatiando.org/verde
  dev_url: https://github.com/fatiando/verde

extra:
  recipe-maintainers:
    - leouieda
