travis:
  secure:
    BINSTAR_TOKEN: Is+i3Lol7KNmHWsCRNj239Z0VJ/N9NRFM559iEoDmPNc7F24odmk3k0AT4UY/ChWahq0wiafzbDV3XrGcTnxzkTeqOnDwh9sJP/kNyzvOcN96PlsT7qxq2Fp/iZGK86RQVirZBh/dSKNHRz1uH+JzgDQ/RWjmNYVnaFF0ccv68avrXFj+Aomrh3AQ5BzdnzbC+NjZ/izqTKy5wSYfqr1rDyR1t7+ergnkJXxmDR2kfm2ahT96xWp0/7DKqmZoXjzxsY46+beoxq2Nm9T8NmutkRmZPEdgnWScgSliUlbQil9XV4dDfkceaKDjtBvCzFE/PJZ9kgM75DMqkP3BDl+3J8MqX2zR9R3CsOO2/glmrJGuPwyXP2mJKYyTY6aLWSrtKvprAZHbWVhsLLuvLL6Fjoivqstt4ASpNBT5HI9EHSsTjZYg6N0I7h7RRI7rN5iTvZDzgAOkA2DbgqMU4h5hAjo7TEywdjUFL+DmSn0LaElcitVZW28sidfRsaSl2Y8b1lYKmZJjM+jpyIuQqv+n0csyARAkS+Lb9J2iFqQfP7wpg1gdSTKZQXO7Zv/smRfd540DyKcbaLu3R2hvDS5F/gzWrIj7SnYn6vW4EuVy1hAZXqhQKdb3M5WkDED9yk2nKWworW6LZGpIen/Vx3x563wGy/dQjPq46cpprRBqFA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
